version: '3'

services:
  mongo:
    ports:
      - 27017:27017

  users:
    ports:
      - 3000:3000

  category:
    ports:
      - 3001:3001

  unit:
    ports:
      - 3002:3002

  api-master:
    ports:
      - 8082:6379
