version: '3'

volumes:
  mongo:
    driver: local

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo:/data/db

  users:
    container_name: users
    build: ./services/users
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"
      SEND_GRID_API_KEY: "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"

  category:
    container_name: categories
    build: ./services/categories
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"

  unit:
    container_name: units
    build: ./services/units
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"

  presentation:
    container_name: presentations
    build: ./services/presentations
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"

  machine:
    container_name: machines
    build: ./services/machines
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"

  process:
    container_name: process
    build: ./services/process
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"

  material:
    container_name: materials
    build: ./services/materials
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"

  provider:
    container_name: providers
    build: ./services/providers
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"

  api-master:
    container_name: api-master
    build: ./api-master
    environment:
      MONGO_URL: "mongodb://mongo/chupiflum"
      USER_URL: "http://users:3000"
      CATEGORY_URL: "http://categories:3001"
      UNIT_URL: "http://units:3002"
      PRESENTATION_URL: "http://presentations:3003"
      MACHINE_URL: "http://machines:3004"
      PROCESS_URL: "http://process:3005"
      MATERIAL_URL: "http://materials:3006"
      PROVIDER_URL: "http://providers:3007"
      SEND_GRID_API_KEY: "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"
